name: houzerd-discord-bot
on:
  push:
    branches: [master]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and Push Docker Image
        # uses: docker/setup-buildx-action@v1
        id: docker_build
        # with:
        #   context: ./
        #   file: ./Dockerfile
        #   builder: ${{ steps.buildx.outputs.name }}
        #   push: true
        #   tags: ${{ secrets.DOCKERHUB_USERNAME }}/houzerd-discord-bot
        run: docker buildx build --platform linux/arm64 -t hoangnh0099/houzerd-discord-bot:latest . && echo ${{ steps.docker_build.platform }}

      # - name: Push Docker Image
      #   id: docker_push
      #   run: docker push hoangnh0099/houzerd-discord-bot:latest

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
